name: Bump version

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  pkg:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Show latest tag
        run: |
          echo ${{ needs.build.outputs.new_tag }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Make package available
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/nutreet/common@${{ needs.build.outputs.new_tag }} > /dev/null || echo "Could not find package"
