name: Auto Tag on Master Push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "::set-output name=tag::$latest_tag"

      - name: Increment tag version
        id: increment_tag
        run: |
          current_tag=${{ steps.latest_tag.outputs.tag }}
          version=$(echo $current_tag | sed -E 's/v([0-9]+.[0-9]+.[0-9]+)/\1/')
          new_version=$(echo $version | awk -F. -v OFS=. '{$NF++; print}')
          new_tag="v$new_version"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create tag
        run: |
          git tag -a ${{ steps.increment_tag.outputs.new_tag }} -m "New tag created"
          git push origin ${{ steps.increment_tag.outputs.new_tag }}
